/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafemanagement;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.*;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author mook
 */


public class menuPage extends javax.swing.JFrame {

    private int bill_id = 1;
    Font font = new Font("Prompt", Font.PLAIN, 15);
    
    public menuPage() {
        initComponents();
        
        UIManager.put("OptionPane.messageFont", font);
        
    }
        
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Bakery = new javax.swing.JButton();
        Reported = new javax.swing.JButton();
        Food = new javax.swing.JButton();
        Drink = new javax.swing.JButton();
        Exit_Button = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        mainMenu = new javax.swing.JPanel();
        FoodPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Red_ake1 = new javax.swing.JPanel();
        KungWunSen_Btn = new javax.swing.JButton();
        Kung_count = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        KapaoKai_Btn = new javax.swing.JButton();
        kapaoKai_count = new javax.swing.JSpinner();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        Makarone_btn = new javax.swing.JButton();
        makarone_count = new javax.swing.JSpinner();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        chocolate_Cake1 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        sapagetti_Btn = new javax.swing.JButton();
        sapagetti_count = new javax.swing.JSpinner();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        Blueberry_Cake2 = new javax.swing.JPanel();
        KapaoSea_Btn = new javax.swing.JButton();
        kapaosea_count = new javax.swing.JSpinner();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        DrinkPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Red_ake2 = new javax.swing.JPanel();
        Coco_btn = new javax.swing.JButton();
        Coco_count = new javax.swing.JSpinner();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        Red_ake3 = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jSpinner18 = new javax.swing.JSpinner();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        Pepsi_Btn = new javax.swing.JButton();
        Pepsi_count = new javax.swing.JSpinner();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        Chatai_btn = new javax.swing.JButton();
        Chatai_count = new javax.swing.JSpinner();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        chocolate_Cake2 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        Water_Btn = new javax.swing.JButton();
        Water_count = new javax.swing.JSpinner();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        Blueberry_Cake3 = new javax.swing.JPanel();
        capucuno_btn = new javax.swing.JButton();
        capucuno_count = new javax.swing.JSpinner();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        Red_ake4 = new javax.swing.JPanel();
        latae_btn = new javax.swing.JButton();
        latae_count = new javax.swing.JSpinner();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        Red_ake5 = new javax.swing.JPanel();
        jButton19 = new javax.swing.JButton();
        jSpinner20 = new javax.swing.JSpinner();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        BakeryPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Red_ake = new javax.swing.JPanel();
        RedCake_count = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        RedCake_btn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        CakeSom_count = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        CakeSom_btn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        banoffee_count = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        banoffee_btn = new javax.swing.JButton();
        chocolate_Cake = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        Chocolate_count = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Chocolate_btn = new javax.swing.JButton();
        Blueberry_Cake1 = new javax.swing.JPanel();
        CheeseCake_count = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        CheeseCake_btn = new javax.swing.JButton();
        Report = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Search_Table = new javax.swing.JTable();
        Search_text = new javax.swing.JTextField();
        Delete_btn = new javax.swing.JButton();
        Search_btn2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        totalPrice_textFeild = new javax.swing.JTextField();
        Price_textFeild = new javax.swing.JTextField();
        Discount_textFeild = new javax.swing.JTextField();
        CheckOut_Btn = new javax.swing.JButton();
        Delete_Order = new javax.swing.JButton();
        ClearOrder_Btn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Table_Order = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Page");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        jPanel3.setBackground(new java.awt.Color(255, 66, 105));

        Bakery.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        Bakery.setText("เบเกอรี่");
        Bakery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BakeryActionPerformed(evt);
            }
        });

        Reported.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        Reported.setText("รายงานผลประจำวัน");
        Reported.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportedActionPerformed(evt);
            }
        });

        Food.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        Food.setText("อาหาร");
        Food.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FoodActionPerformed(evt);
            }
        });

        Drink.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        Drink.setText("เครื่องดื่ม");
        Drink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrinkActionPerformed(evt);
            }
        });

        Exit_Button.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        Exit_Button.setText("ออกจากโปรเเกรม");
        Exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Food, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bakery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Drink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Reported, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(Exit_Button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Food, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Bakery, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Drink, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Reported, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                .addComponent(Exit_Button)
                .addGap(15, 15, 15))
        );

        jPanel1.setBackground(new java.awt.Color(255, 66, 105));

        jLabel2.setBackground(new java.awt.Color(242, 111, 129));
        jLabel2.setFont(new java.awt.Font("Prompt", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cafe Menu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(454, 454, 454)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        mainMenu.setPreferredSize(new java.awt.Dimension(800, 700));
        mainMenu.setLayout(new java.awt.CardLayout());

        FoodPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Prompt", 0, 36)); // NOI18N
        jLabel1.setText("อาหาร");
        FoodPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, -1));

        Red_ake1.setBackground(new java.awt.Color(255, 153, 153));
        Red_ake1.setPreferredSize(new java.awt.Dimension(200, 280));
        Red_ake1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        KungWunSen_Btn.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        KungWunSen_Btn.setText("เพิ่ม");
        KungWunSen_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KungWunSen_BtnActionPerformed(evt);
            }
        });
        Red_ake1.add(KungWunSen_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 70, 20));
        Red_ake1.add(Kung_count, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, 20));

        jLabel10.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("กุ้งอบวุ้นเส้น");
        Red_ake1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Kung.jpg"))); // NOI18N
        Red_ake1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 201, -1));

        jLabel26.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("ราคา : 70");
        Red_ake1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        FoodPanel.add(Red_ake1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 220, -1));

        jPanel8.setBackground(new java.awt.Color(255, 153, 153));
        jPanel8.setPreferredSize(new java.awt.Dimension(200, 280));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        KapaoKai_Btn.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        KapaoKai_Btn.setText("เพิ่ม");
        KapaoKai_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KapaoKai_BtnActionPerformed(evt);
            }
        });
        jPanel8.add(KapaoKai_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 20));
        jPanel8.add(kapaoKai_count, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, 20));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kapao.jpg"))); // NOI18N
        jPanel8.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 206));

        jLabel28.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("กะเพราไก่");
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel29.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("ราคา :  50");
        jPanel8.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        FoodPanel.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 220, 280));

        jPanel9.setBackground(new java.awt.Color(255, 153, 153));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/macaroni.png"))); // NOI18N
        jPanel9.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 190));

        Makarone_btn.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        Makarone_btn.setText("เพิ่ม");
        Makarone_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Makarone_btnActionPerformed(evt);
            }
        });
        jPanel9.add(Makarone_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 20));
        jPanel9.add(makarone_count, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, 20));

        jLabel31.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("มักกะโรนี");
        jPanel9.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 70, 20));

        jLabel32.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("ราคา :  60");
        jPanel9.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        FoodPanel.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 220, 280));

        chocolate_Cake1.setBackground(new java.awt.Color(255, 153, 153));
        chocolate_Cake1.setPreferredSize(new java.awt.Dimension(200, 280));
        chocolate_Cake1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cabo.jpg"))); // NOI18N
        chocolate_Cake1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 200));

        sapagetti_Btn.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        sapagetti_Btn.setText("เพิ่ม");
        sapagetti_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sapagetti_BtnActionPerformed(evt);
            }
        });
        chocolate_Cake1.add(sapagetti_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 20));
        chocolate_Cake1.add(sapagetti_count, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 70, 20));

        jLabel34.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("สปาเก็ตตี้คาโบนาร่า");
        chocolate_Cake1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel35.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("ราคา : 70");
        chocolate_Cake1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        FoodPanel.add(chocolate_Cake1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 220, -1));

        Blueberry_Cake2.setBackground(new java.awt.Color(255, 153, 153));
        Blueberry_Cake2.setPreferredSize(new java.awt.Dimension(200, 280));
        Blueberry_Cake2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        KapaoSea_Btn.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        KapaoSea_Btn.setText("เพิ่ม");
        KapaoSea_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KapaoSea_BtnActionPerformed(evt);
            }
        });
        Blueberry_Cake2.add(KapaoSea_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 20));
        Blueberry_Cake2.add(kapaosea_count, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, 20));

        jLabel36.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("ข้าวกะเพราทะเล");
        Blueberry_Cake2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kapaoSea.jpg"))); // NOI18N
        Blueberry_Cake2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel38.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("ราคา : 60");
        Blueberry_Cake2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        FoodPanel.add(Blueberry_Cake2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 220, -1));

        mainMenu.add(FoodPanel, "card2");

        DrinkPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Prompt", 0, 36)); // NOI18N
        jLabel4.setText("เครื่องดื่ม");
        DrinkPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Red_ake2.setBackground(new java.awt.Color(255, 153, 153));
        Red_ake2.setPreferredSize(new java.awt.Dimension(200, 280));
        Red_ake2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Coco_btn.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        Coco_btn.setText("เพิ่ม");
        Coco_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Coco_btnActionPerformed(evt);
            }
        });
        Red_ake2.add(Coco_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 20));
        Red_ake2.add(Coco_count, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, 20));

        jLabel39.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("โกโก้");
        Red_ake2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, 20));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/koko.jpg"))); // NOI18N
        Red_ake2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 201, -1));

        jLabel41.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("ราคา : 50");
        Red_ake2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        Red_ake3.setBackground(new java.awt.Color(255, 153, 153));
        Red_ake3.setPreferredSize(new java.awt.Dimension(200, 280));
        Red_ake3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton17.setText("เพิ่ม");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        Red_ake3.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));
        Red_ake3.add(jSpinner18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, 23));

        jLabel54.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("ลาเต้");
        Red_ake3.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/red.jpg"))); // NOI18N
        Red_ake3.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 201, -1));

        jLabel56.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("ราคา : 50");
        Red_ake3.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        Red_ake2.add(Red_ake3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 220, -1));

        DrinkPanel.add(Red_ake2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 220, -1));

        jPanel10.setBackground(new java.awt.Color(255, 153, 153));
        jPanel10.setPreferredSize(new java.awt.Dimension(200, 280));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pepsi_Btn.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        Pepsi_Btn.setText("เพิ่ม");
        Pepsi_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pepsi_BtnActionPerformed(evt);
            }
        });
        jPanel10.add(Pepsi_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 20));
        jPanel10.add(Pepsi_count, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, 20));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/15.jpg"))); // NOI18N
        jPanel10.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 206));

        jLabel43.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("น้ำอัดลม");
        jPanel10.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, 20));

        jLabel44.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("ราคา :  25");
        jPanel10.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        DrinkPanel.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 220, 280));

        jPanel11.setBackground(new java.awt.Color(255, 153, 153));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/9.jpg"))); // NOI18N
        jPanel11.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        Chatai_btn.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        Chatai_btn.setText("เพิ่ม");
        Chatai_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chatai_btnActionPerformed(evt);
            }
        });
        jPanel11.add(Chatai_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 20));
        jPanel11.add(Chatai_count, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, 20));

        jLabel46.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("ชาไทย");
        jPanel11.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 50, 20));

        jLabel47.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("ราคา :  50");
        jPanel11.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        DrinkPanel.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 220, 280));

        chocolate_Cake2.setBackground(new java.awt.Color(255, 153, 153));
        chocolate_Cake2.setPreferredSize(new java.awt.Dimension(200, 280));
        chocolate_Cake2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/6.jpg"))); // NOI18N
        chocolate_Cake2.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 210));

        Water_Btn.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        Water_Btn.setText("เพิ่ม");
        Water_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Water_BtnActionPerformed(evt);
            }
        });
        chocolate_Cake2.add(Water_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 20));
        chocolate_Cake2.add(Water_count, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, 20));

        jLabel49.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("น้ำเปล่า");
        chocolate_Cake2.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, 20));

        jLabel50.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("ราคา : 15");
        chocolate_Cake2.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        DrinkPanel.add(chocolate_Cake2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 220, -1));

        Blueberry_Cake3.setBackground(new java.awt.Color(255, 153, 153));
        Blueberry_Cake3.setPreferredSize(new java.awt.Dimension(200, 280));
        Blueberry_Cake3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        capucuno_btn.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        capucuno_btn.setText("เพิ่ม");
        capucuno_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capucuno_btnActionPerformed(evt);
            }
        });
        Blueberry_Cake3.add(capucuno_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 20));
        Blueberry_Cake3.add(capucuno_count, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, 20));

        jLabel51.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("คาปูชิโน่");
        Blueberry_Cake3.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, 20));

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/10.jpg"))); // NOI18N
        Blueberry_Cake3.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel53.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("ราคา : 50");
        Blueberry_Cake3.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        DrinkPanel.add(Blueberry_Cake3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 220, -1));

        Red_ake4.setBackground(new java.awt.Color(255, 153, 153));
        Red_ake4.setPreferredSize(new java.awt.Dimension(200, 280));
        Red_ake4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        latae_btn.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        latae_btn.setText("เพิ่ม");
        latae_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                latae_btnActionPerformed(evt);
            }
        });
        Red_ake4.add(latae_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 20));
        Red_ake4.add(latae_count, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, 20));

        jLabel57.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("ลาเต้");
        Red_ake4.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, 20));

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/12.jpg"))); // NOI18N
        Red_ake4.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 201, -1));

        jLabel59.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("ราคา : 50");
        Red_ake4.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 60, -1));

        Red_ake5.setBackground(new java.awt.Color(255, 153, 153));
        Red_ake5.setPreferredSize(new java.awt.Dimension(200, 280));
        Red_ake5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton19.setText("เพิ่ม");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        Red_ake5.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));
        Red_ake5.add(jSpinner20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, 23));

        jLabel60.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("ลาเต้");
        Red_ake5.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/red.jpg"))); // NOI18N
        Red_ake5.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 201, -1));

        jLabel62.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setText("ราคา : 50");
        Red_ake5.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        Red_ake4.add(Red_ake5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 220, -1));

        DrinkPanel.add(Red_ake4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 220, -1));

        mainMenu.add(DrinkPanel, "card4");

        BakeryPanel.setMaximumSize(new java.awt.Dimension(800, 700));
        BakeryPanel.setPreferredSize(new java.awt.Dimension(2000, 724));
        BakeryPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Prompt", 0, 36)); // NOI18N
        jLabel5.setText("เบเกอรี่");
        BakeryPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Red_ake.setBackground(new java.awt.Color(255, 153, 153));
        Red_ake.setPreferredSize(new java.awt.Dimension(200, 280));
        Red_ake.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Red_ake.add(RedCake_count, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, 20));

        jLabel3.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("เค้กเรดเวลเวท");
        Red_ake.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, 20));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/red.jpg"))); // NOI18N
        Red_ake.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 201, -1));

        jLabel17.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("ราคา :85");
        Red_ake.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        RedCake_btn.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        RedCake_btn.setText("เพิ่ม");
        RedCake_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RedCake_btnActionPerformed(evt);
            }
        });
        Red_ake.add(RedCake_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 20));

        BakeryPanel.add(Red_ake, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 220, -1));

        jPanel5.setBackground(new java.awt.Color(255, 153, 153));
        jPanel5.setMinimumSize(new java.awt.Dimension(210, 263));
        jPanel5.setPreferredSize(new java.awt.Dimension(200, 280));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(CakeSom_count, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, 20));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Som.jpg"))); // NOI18N
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 206));

        jLabel6.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("เค้กลูกส้ม");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, 20));

        jLabel22.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("ราคา :  80");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        CakeSom_btn.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        CakeSom_btn.setText("เพิ่ม");
        CakeSom_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CakeSom_btnActionPerformed(evt);
            }
        });
        jPanel5.add(CakeSom_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 20));

        BakeryPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 220, 280));

        jPanel6.setBackground(new java.awt.Color(255, 153, 153));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/banof.jpg"))); // NOI18N
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));
        jPanel6.add(banoffee_count, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, 20));

        jLabel7.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("เค้กบานอฟฟี่");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 100, 20));

        jLabel18.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("ราคา :  60");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        banoffee_btn.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        banoffee_btn.setText("เพิ่ม");
        banoffee_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banoffee_btnActionPerformed(evt);
            }
        });
        jPanel6.add(banoffee_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 20));

        BakeryPanel.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 220, 280));

        chocolate_Cake.setBackground(new java.awt.Color(255, 153, 153));
        chocolate_Cake.setPreferredSize(new java.awt.Dimension(200, 280));
        chocolate_Cake.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/p79.jpg"))); // NOI18N
        chocolate_Cake.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 210));
        chocolate_Cake.add(Chocolate_count, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, 20));

        jLabel8.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("เค้กช็อกโกแลตหน้านิ่ม");
        chocolate_Cake.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 20));

        jLabel23.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("ราคา : 85");
        chocolate_Cake.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        Chocolate_btn.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        Chocolate_btn.setText("เพิ่ม");
        Chocolate_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chocolate_btnActionPerformed(evt);
            }
        });
        chocolate_Cake.add(Chocolate_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 20));

        BakeryPanel.add(chocolate_Cake, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 220, -1));

        Blueberry_Cake1.setBackground(new java.awt.Color(255, 153, 153));
        Blueberry_Cake1.setPreferredSize(new java.awt.Dimension(200, 280));
        Blueberry_Cake1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Blueberry_Cake1.add(CheeseCake_count, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, 20));

        jLabel9.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ชีสเค้กบลูเบอร์รี่");
        Blueberry_Cake1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, 20));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cocokup.jpg"))); // NOI18N
        Blueberry_Cake1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel24.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("ราคา : 90");
        Blueberry_Cake1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        CheeseCake_btn.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        CheeseCake_btn.setText("เพิ่ม");
        CheeseCake_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheeseCake_btnActionPerformed(evt);
            }
        });
        Blueberry_Cake1.add(CheeseCake_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 20));

        BakeryPanel.add(Blueberry_Cake1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 220, -1));

        mainMenu.add(BakeryPanel, "card3");

        Report.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Prompt", 0, 36)); // NOI18N
        jLabel13.setText("รายงานผลประจำวัน");
        Report.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Search_Table.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        Search_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "order ID", "Total Price", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Search_Table.setToolTipText("");
        Search_Table.setRowHeight(40);
        Search_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Search_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Search_Table);

        Report.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 650, 500));

        Search_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Search_textKeyReleased(evt);
            }
        });
        Report.add(Search_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 300, 30));

        Delete_btn.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        Delete_btn.setText("ลบ");
        Delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_btnActionPerformed(evt);
            }
        });
        Report.add(Delete_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, -1, 30));

        Search_btn2.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        Search_btn2.setText("ค้นหาทั้งหมด");
        Search_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_btn2ActionPerformed(evt);
            }
        });
        Report.add(Search_btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, -1, 30));

        mainMenu.add(Report, "card6");

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        jLabel19.setText("ราคา :");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 50, 30));

        jLabel20.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        jLabel20.setText("ส่วนลด :");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 70, 30));

        jLabel21.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        jLabel21.setText("ราคาทั้งหมด :");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 110, 30));

        totalPrice_textFeild.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        totalPrice_textFeild.setEnabled(false);
        jPanel7.add(totalPrice_textFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 250, 30));

        Price_textFeild.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Price_textFeild.setEnabled(false);
        jPanel7.add(Price_textFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 250, 30));

        Discount_textFeild.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Discount_textFeild.setEnabled(false);
        jPanel7.add(Discount_textFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 250, 30));

        CheckOut_Btn.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        CheckOut_Btn.setText("คำนวน");
        CheckOut_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOut_BtnActionPerformed(evt);
            }
        });
        jPanel7.add(CheckOut_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 110, 40));

        Delete_Order.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        Delete_Order.setText("ลบรายการ");
        Delete_Order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_OrderActionPerformed(evt);
            }
        });
        jPanel7.add(Delete_Order, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 100, 40));

        ClearOrder_Btn.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        ClearOrder_Btn.setText("เคลียร์ออเดอร์");
        ClearOrder_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearOrder_BtnActionPerformed(evt);
            }
        });
        jPanel7.add(ClearOrder_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 110, 40));

        Table_Order.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        Table_Order.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Table_Order.setRowHeight(30);
        jScrollPane3.setViewportView(Table_Order);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(mainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrinkActionPerformed
        // DefaultTableModel model = (DefaultTableModel) Table_Order.getModel();
        // model.setRowCount(0);
        // totalPrice_textFeild.setText("");
        // Price_textFeild.setText("");
        // Discount_textFeild.setText("");
        FoodPanel.setVisible(false);
        BakeryPanel.setVisible(false);
        DrinkPanel.setVisible(true);
        Report.setVisible(false);
    }//GEN-LAST:event_DrinkActionPerformed

    private void FoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FoodActionPerformed
        // DefaultTableModel model = (DefaultTableModel) Table_Order.getModel();
        // model.setRowCount(0);
        // totalPrice_textFeild.setText("");
        // Price_textFeild.setText("");
        // Discount_textFeild.setText("");

        FoodPanel.setVisible(true);
        BakeryPanel.setVisible(false);
        DrinkPanel.setVisible(false);
        Report.setVisible(false);
    }//GEN-LAST:event_FoodActionPerformed

    private void ReportedActionPerformed(java.awt.event.ActionEvent evt) {
        
        FoodPanel.setVisible(false);
        BakeryPanel.setVisible(false);
        DrinkPanel.setVisible(false);
        Report.setVisible(true);


        // !CREATE FUNCTION TO SHOW REPORT
    
        LocalDateTime myDateObj = LocalDateTime.now();  
        DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("yyyy-MM-dd");  
        String formattedDate = myDateObj.format(myFormatObj); 
        String query = "SELECT * FROM bills WHERE bill_date = '"+formattedDate+"'";
        DefaultTableModel model = (DefaultTableModel) Search_Table.getModel();
        model.setRowCount(0);
        try {
            Database db = new Database();
            db.getConnect();
            ResultSet rs = db.getStatement().executeQuery(query);
            int i = 1;
            while (rs.next()) {
                
                String bill_id = rs.getString("bill_id");
                String date = rs.getString("bill_date");
                String total_amount = rs.getString("total_amount");
                
                
               
                Object[] row = { i,bill_id,total_amount, date };
                i++;
                model.addRow(row);

                
                
            }
            db.disconect();
        } catch (Exception e) {
           e.printStackTrace();
        }



    }                                        

    private void BakeryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BakeryActionPerformed
        // DefaultTableModel model = (DefaultTableModel) Table_Order.getModel();
        // model.setRowCount(0);
        // totalPrice_textFeild.setText("");
        // Price_textFeild.setText("");
        // Discount_textFeild.setText("");
        FoodPanel.setVisible(false);
        BakeryPanel.setVisible(true);
        DrinkPanel.setVisible(false);
        Report.setVisible(false);
    }//GEN-LAST:event_BakeryActionPerformed

    private void KungWunSen_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KungWunSen_BtnActionPerformed
        int count = (int) Kung_count.getValue();
        
        if (count >= 1) {
            
            JOptionPane.showMessageDialog(null, "คุณได้เพิ่ม กุ้งอบวุ้นเส้น ราคา: 70 บาท จำนวน "+ count, "Add Order", 3);
            // !CREATE FUNCTION TO ADD PRODUCT 
            addOrderToTable("กุ้งอบวุ้นเส้น", "70", count);
            Kung_count.setValue(0);
        } else {
            Kung_count.setValue(0);
            JOptionPane.showMessageDialog(null, "กรุณาใส่จำนวนสินค้าที่ต้องการ", "Warning", 2);
        }
    }//GEN-LAST:event_KungWunSen_BtnActionPerformed

    private void KapaoKai_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KapaoKai_BtnActionPerformed

        int count = (int) kapaoKai_count.getValue();
        if (count >= 1) {
            
            JOptionPane.showMessageDialog(null, "คุณได้เพิ่ม กะเพราไก่ ราคา: 50 บาท จำนวน "+ count, "Add Order", 3);
            // !CREATE FUNCTION TO ADD PRODUCT 
            addOrderToTable("กะเพราไก่", "50", count);
            kapaoKai_count.setValue(0);
        } else {
            kapaoKai_count.setValue(0);
            JOptionPane.showMessageDialog(null, "กรุณาใส่จำนวนสินค้าที่ต้องการ", "Warning", 2);
        }

    }//GEN-LAST:event_KapaoKai_BtnActionPerformed

    private void Makarone_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Makarone_btnActionPerformed
       
        int count = (int) makarone_count.getValue();
        if (count >= 1)
        {
            
        JOptionPane.showMessageDialog(null, "คุณได้เพิ่ม มักกะโรนี ราคา: 60 บาท จำนวน "+ count, "Add Order", 3);
        // !CREATE FUNCTION TO ADD PRODUCT 
        addOrderToTable("มักกะโรนี", "60", count);
        makarone_count.setValue(0);
        } else {
            makarone_count.setValue(0);
            JOptionPane.showMessageDialog(null, "กรุณาใส่จำนวนสินค้าที่ต้องการ", "Warning", 2);
        }
    }//GEN-LAST:event_Makarone_btnActionPerformed

    private void sapagetti_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sapagetti_BtnActionPerformed
        int count = (int) sapagetti_count.getValue();
        if (count >= 1) {
            
            JOptionPane.showMessageDialog(null, "คุณได้เพิ่ม สปาเก็ตตี้คาโบนาร่า ราคา: 70 บาท จำนวน "+ count, "Add Order", 3);
            // !CREATE FUNCTION TO ADD PRODUCT 
            addOrderToTable("สปาเก็ตตี้คาโบนาร่า", "70", count);
            sapagetti_count.setValue(0);

        } else {
            sapagetti_count.setValue(0);
            JOptionPane.showMessageDialog(null, "กรุณาใส่จำนวนสินค้าที่ต้องการ", "Warning", 2);
        }


    }//GEN-LAST:event_sapagetti_BtnActionPerformed

    private void KapaoSea_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KapaoSea_BtnActionPerformed
        int count = (int) kapaosea_count.getValue();
        if (count >= 1) {
            
            JOptionPane.showMessageDialog(null, "คุณได้เพิ่ม ข้าวกะเพราทะเล ราคา: 60 บาท จำนวน "+ count, "Add Order", 3);
            // !CREATE FUNCTION TO ADD PRODUCT 
            addOrderToTable("ข้าวกะเพราทะเล", "60", count);
            kapaosea_count.setValue(0);
        } else {
            kapaosea_count.setValue(0);
            JOptionPane.showMessageDialog(null, "กรุณาใส่จำนวนสินค้าที่ต้องการ", "Warning", 2);
        }
       
    }//GEN-LAST:event_KapaoSea_BtnActionPerformed

    private void Coco_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Coco_btnActionPerformed
        int count = (int) Coco_count.getValue();
        if (count >= 1) {
            
            JOptionPane.showMessageDialog(null, "คุณได้เพิ่ม โกโก้ ราคา: 50 บาท จำนวน "+ count, "Add Order", 3);
            // !CREATE FUNCTION TO ADD PRODUCT 
            addOrderToTable("โกโก้", "50", count);
            Coco_count.setValue(0);
        } else {
            Coco_count.setValue(0);
            JOptionPane.showMessageDialog(null, "กรุณาใส่จำนวนสินค้าที่ต้องการ", "Warning", 2);
        }
    }//GEN-LAST:event_Coco_btnActionPerformed

    private void Pepsi_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pepsi_BtnActionPerformed
        int count = (int) Pepsi_count.getValue();
        if (count >= 1) {
            
            JOptionPane.showMessageDialog(null, "คุณได้เพิ่ม น้ำอัดลม ราคา: 25 บาท จำนวน "+ count, "Add Order", 3);
            // !CREATE FUNCTION TO ADD PRODUCT 
            addOrderToTable("น้ำอัดลม", "25", count);
            Pepsi_count.setValue(0);
        } else {
            Pepsi_count.setValue(0);
            JOptionPane.showMessageDialog(null, "กรุณาใส่จำนวนสินค้าที่ต้องการ", "Warning", 2);
        }
    }//GEN-LAST:event_Pepsi_BtnActionPerformed

    private void Chatai_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chatai_btnActionPerformed
        int count = (int) Chatai_count.getValue();
        if (count >= 1) {
            
            JOptionPane.showMessageDialog(null, "คุณได้เพิ่ม ชาไทย ราคา: 50 บาท จำนวน "+ count, "Add Order", 3);
            // !CREATE FUNCTION TO ADD PRODUCT 
            addOrderToTable("ชาไทย", "50", count);
            Chatai_count.setValue(0);
        } else {
            Chatai_count.setValue(0);
            JOptionPane.showMessageDialog(null, "กรุณาใส่จำนวนสินค้าที่ต้องการ", "Warning", 2);
        }
            
    }//GEN-LAST:event_Chatai_btnActionPerformed

    private void Water_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Water_BtnActionPerformed
        int count = (int) Water_count.getValue();
        if (count >= 1) {
            
            JOptionPane.showMessageDialog(null, "คุณได้เพิ่ม น้ำเปล่า ราคา: 15 บาท จำนวน "+ count, "Add Order", 3);
            // !CREATE FUNCTION TO ADD PRODUCT 
            addOrderToTable("น้ำเปล่า", "15", count);
            Water_count.setValue(0);
        } else {
            Water_count.setValue(0);
            JOptionPane.showMessageDialog(null, "กรุณาใส่จำนวนสินค้าที่ต้องการ", "Warning", 2);
        }
    }//GEN-LAST:event_Water_BtnActionPerformed

    private void capucuno_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capucuno_btnActionPerformed
        int count = (int) capucuno_count.getValue();
        if (count >= 1) {
            
            JOptionPane.showMessageDialog(null, "คุณได้เพิ่ม คาปูชิโน่ ราคา: 50 บาท จำนวน "+ count, "Add Order", 3);
            // !CREATE FUNCTION TO ADD PRODUCT 
            addOrderToTable("คาปูชิโน่", "50", count);
            capucuno_count.setValue(0);
        } else {
            capucuno_count.setValue(0);
            JOptionPane.showMessageDialog(null, "กรุณาใส่จำนวนสินค้าที่ต้องการ", "Warning", 2);
        }
    }//GEN-LAST:event_capucuno_btnActionPerformed

    private void CheckOut_BtnActionPerformed(java.awt.event.ActionEvent evt) {
        
        String discount_txt = Discount_textFeild.getText();
        int discount;
        int totalPrice = 0;
       
        
        
        if (Table_Order.getRowCount() != 0 ) 
        {
           
            System.out.println("==========");

            for (int i = 0; i < Table_Order.getRowCount(); i++) {
                String price = (String) Table_Order.getValueAt(i, 1);
                int amount = Integer.parseInt(Table_Order.getValueAt(i, 2).toString());
                totalPrice += Integer.parseInt(price) * amount;
            }
            System.out.println("==========");
        } else {
            JOptionPane.showMessageDialog(null, "กรุณาเพิ่มสินค้าในตะกร้าก่อน", "Warning", 2);

        }

        

        if (totalPrice >= 100 && totalPrice < 200) {
            discount = 5;
            Discount_textFeild.setText("5");
        } else if (totalPrice >= 200 && totalPrice < 300) {
            discount = 10;
            Discount_textFeild.setText("10");
        } else if (totalPrice >= 300) {
            discount = 20;
            Discount_textFeild.setText("20");
        } else {
            discount = 0;
            if ( Table_Order.getRowCount() != 0 ) {
                JTextArea text = new JTextArea();
                text.setFont(font);
                text.append("[!] คุณไม่มีส่วนลด\n");
                text.append("เงื่อนไขการใช้ส่วนลด\n");
                text.append("1. ซื้อสินค้าครบ 100 บาท ขึ้นไป ลด 5 บาท\n");
                text.append("2. ซื้อสินค้าครบ 200 บาท ขึ้นไป ลด 10 บาท\n");
                text.append("3. ซื้อสินค้าครบ 300 บาท ขึ้นไป ลด 20 บาท");
                text.setFont(font);
                JOptionPane.showMessageDialog(null,text , "alert", 1);
                // Price_textFeild.setText("");
                Discount_textFeild.setText("");
                // totalPrice_textFeild.setText("");

            }
            

        }
        int total = totalPrice - discount;
        totalPrice_textFeild.setText(String.valueOf(total));
        if ( Table_Order.getRowCount() != 0 ) {
            JTextArea text = new JTextArea();
            text.setFont(font);
            text.append("คุณได้ทำการสั่งซื้อสินค้าเรียบร้อย\n");
            text.append("========================================\n");
            text.append("รายการสินค้าที่สั่งซื้อ\n");
            for (int i = 0; i < Table_Order.getRowCount(); i++) {
                String price = (String) Table_Order.getValueAt(i, 1);
                String amount = Table_Order.getValueAt(i, 2).toString();
                text.append("รายการที่ : "+(i+1)+" :" + Table_Order.getValueAt(i, 0) + " จำนวน: " + amount + " ราคา: " + price + " บาท\n");
                // text.append(String.valueOf(total));
            }
            text.append("========================================\n");
            text.append("ราคาสินค้าทั้งหมด: " + totalPrice + " บาท\n");
            JOptionPane.showMessageDialog(null, text, "ALERT", 1);
            Price_textFeild.setText(String.valueOf(totalPrice));
        } else {
            Price_textFeild.setText("");
            Discount_textFeild.setText("");
            totalPrice_textFeild.setText("");
        }
        Price_textFeild.setText(String.valueOf(totalPrice));

        if (Table_Order.getRowCount() != 0 ) 
        {
           
            System.out.println("==========");

            int confirm = JOptionPane.showConfirmDialog(null, "คุณต้องการทำรายการต่อหรือไม่\n[หมายเหตุ] หากตอบ [No] ระบบจะทำการบันทึกรายการสั่งซื้อ", "Confirm", JOptionPane.YES_NO_OPTION);
            System.out.println("This is Answer : "+confirm);
            if (confirm == 1) {
                JOptionPane.showMessageDialog(null, "บันทึกรายการขาย", "Alert", 1);
    
                //! Create Function to Save Order
                LocalDateTime myDateObj = LocalDateTime.now();  
                DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("yyyy-MM-dd");  
                String formattedDate = myDateObj.format(myFormatObj);  
                String text_Total = totalPrice_textFeild.getText();

                String query = "INSERT INTO bills (bill_date, total_amount) VALUES ('"+formattedDate+"', '"+text_Total+"')";
                System.out.println(query);
                try {
                    Database db = new Database();
                    db.getConnect();
                    db.getStatement().executeUpdate(query);
                    db.disconect();
                } catch (Exception e) {
                    e.printStackTrace();
                }
                


                for (int i = 0; i < Table_Order.getRowCount(); i++) {
                    String name = (String) Table_Order.getValueAt(i, 0);
                    String price = (String) Table_Order.getValueAt(i, 1);
                    String amount = Table_Order.getValueAt(i, 2).toString();
                    String query2 = "INSERT INTO bill_items (bill_id, product_name, price, quantity) VALUES ('"+getLatestBillID()+"', '"+name+"', '"+price+"', '"+amount+"')";
                    System.out.println(query2);
                    try {
                        Database db = new Database();
                        db.getConnect();
                        db.getStatement().executeUpdate(query2);
                        db.disconect();
                        
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
                DefaultTableModel model = (DefaultTableModel) Table_Order.getModel();
                model.setRowCount(0);
                Price_textFeild.setText("");
                Discount_textFeild.setText("");
                totalPrice_textFeild.setText("");
                
                this.bill_id++;

                


               
    
            } else {
                JOptionPane.showMessageDialog(null, "ทำรายการต่อ", "Alert", 1);
                
            }
            System.out.println("==========");
        } else {
            // JOptionPane.showMessageDialog(null, "กรุณาเพิ่มสินค้าในตะกร้าก่อน", "Warning", 2);

        }
        
        
    }

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed

    }//GEN-LAST:event_jButton17ActionPerformed

    private void latae_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_latae_btnActionPerformed
        int count = (int) latae_count.getValue();
        if (count >= 1) {
            
            JOptionPane.showMessageDialog(null, "คุณได้เพิ่ม ลาเต้ ราคา: 50 บาท จำนวน "+ count, "Add Order", 3);
            // !CREATE FUNCTION TO ADD PRODUCT 
            addOrderToTable("ลาเต้", "50", count);
            latae_count.setValue(0);

        } else {
            latae_count.setValue(0);
            JOptionPane.showMessageDialog(null, "กรุณาใส่จำนวนสินค้าที่ต้องการ", "Warning", 2);
        }
    }//GEN-LAST:event_latae_btnActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        
    }//GEN-LAST:event_jButton19ActionPerformed

    private void CakeSom_btnActionPerformed(java.awt.event.ActionEvent evt) {
        int count = (int) CakeSom_count.getValue();
        if (count >= 1) {
            
            JOptionPane.showMessageDialog(null, "คุณได้เพิ่ม เค้กลูกส้ม ราคา: 80 บาท จำนวน "+ count, "Add Order", 3);
            // !CREATE FUNCTION TO ADD PRODUCT 
            addOrderToTable("เค้กลูกส้ม", "80", count);
            CakeSom_count.setValue(0);

        } else {
            CakeSom_count.setValue(0);
            JOptionPane.showMessageDialog(null, "กรุณาใส่จำนวนสินค้าที่ต้องการ", "Warning", 2);
        }
        
    }

    private void Chocolate_btnActionPerformed(java.awt.event.ActionEvent evt) {
        int count = (int) Chocolate_count.getValue();
        if (count >= 1) {
            
            JOptionPane.showMessageDialog(null, "คุณได้เพิ่ม เค้กช็อกโกแลตหน้านิ่ม ราคา: 85 บาท จำนวน "+ count, "Add Order", 3);
            // !CREATE FUNCTION TO ADD PRODUCT 
            addOrderToTable("เค้กช็อกโกแลตหน้านิ่ม", "85", count);
            Chocolate_count.setValue(0);
        } else {
            Chocolate_count.setValue(0);
            JOptionPane.showMessageDialog(null, "กรุณาใส่จำนวนสินค้าที่ต้องการ", "Warning", 2);
        }
    }

    private void banoffee_btnActionPerformed(java.awt.event.ActionEvent evt) {
        int count = (int) banoffee_count.getValue();
        if (count >= 1) {
            
            JOptionPane.showMessageDialog(null, "คุณได้เพิ่ม เค้กบานอฟฟี่ ราคา: 60 บาท จำนวน "+ count, "Add Order", 3);
            // !CREATE FUNCTION TO ADD PRODUCT 
            addOrderToTable("เค้กบานอฟฟี่", "60", count);
            banoffee_count.setValue(0);
        } else {
            banoffee_count.setValue(0);
            JOptionPane.showMessageDialog(null, "กรุณาใส่จำนวนสินค้าที่ต้องการ", "Warning", 2);
        }
        
    }

    private void CheeseCake_btnActionPerformed(java.awt.event.ActionEvent evt) {
        int count = (int) CheeseCake_count.getValue();
        if (count >= 1) {
            
            JOptionPane.showMessageDialog(null, "คุณได้เพิ่ม ชีสเค้กบลูเบอร์รี่ ราคา: 90 บาท จำนวน "+ count, "Add Order", 3);
            // !CREATE FUNCTION TO ADD PRODUCT
            addOrderToTable("ชีสเค้กบลูเบอร์รี่", "90", count); 
            CheeseCake_count.setValue(0);
        } else {
            CheeseCake_count.setValue(0);
            JOptionPane.showMessageDialog(null, "กรุณาใส่จำนวนสินค้าที่ต้องการ", "Warning", 2);
        }
    }

    private void RedCake_btnActionPerformed(java.awt.event.ActionEvent evt) {
       int count = (int) RedCake_count.getValue();
        if (count >= 1) {
            
            JOptionPane.showMessageDialog(null, "คุณได้เพิ่ม เค้กเรดเวลเวท ราคา: 85 บาท จำนวน "+ count, "Add Order", 3);
            // !CREATE FUNCTION TO ADD PRODUCT
            addOrderToTable("เค้กเรดเวลเวท", "85", count); 
            RedCake_count.setValue(0);
        } else {
            RedCake_count.setValue(0);
            JOptionPane.showMessageDialog(null, "กรุณาใส่จำนวนสินค้าที่ต้องการ", "Warning", 2);
        }
    }//GEN-LAST:event_RedCake_btnActionPerformed

    private void Delete_OrderActionPerformed(java.awt.event.ActionEvent evt) {
        int countRow = Table_Order.getSelectedRowCount();
        int selectedRow = Table_Order.getSelectedRow();
        int confirm = JOptionPane.showConfirmDialog(this, "คุณเเน่ใช่หรือไม่ว่าต้องการลบ รายการนี้ !", "Confirm Alert", JOptionPane.YES_NO_OPTION);


        if (confirm == JOptionPane.YES_OPTION) {
            
        
            if (countRow != 0) {
                if (countRow > 1)
                {
                    JOptionPane.showMessageDialog(null, "เลือกได้เเค่ 1 รายการ", "Alert", 0);
                }else 
                {
                    DefaultTableModel model = (DefaultTableModel) Table_Order.getModel();
                    model.removeRow(selectedRow);
                }
                
                
            } else {
                JOptionPane.showMessageDialog(null, "คุณไม่มีรายการที่เลือก.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            upDatePrice();

           
        }

        
    }

    private void Exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
        welcome welcomeFrame = new welcome();
        welcomeFrame.setVisible(true);
    }//GEN-LAST:event_Exit_ButtonActionPerformed

    private void ClearOrder_BtnActionPerformed(java.awt.event.ActionEvent evt) {
        DefaultTableModel model = (DefaultTableModel) Table_Order.getModel();
        model.setRowCount(0);
        Price_textFeild.setText("");
        Discount_textFeild.setText("");
        totalPrice_textFeild.setText("");
    }

    private void Search_btn2ActionPerformed(java.awt.event.ActionEvent evt) {
        // ค้นหาทั้งหมด
        String query = "SELECT * FROM bills";
        DefaultTableModel model = (DefaultTableModel) Search_Table.getModel();
        model.setRowCount(0);
        try {
            Database db = new Database();
            db.getConnect();
            ResultSet rs = db.getStatement().executeQuery(query);
            int i = 1;
            while (rs.next()) {
                
                String bill_id = rs.getString("bill_id");
                String date = rs.getString("bill_date");
                String total_amount = rs.getString("total_amount");

                Object[] row = { i,bill_id,total_amount, date };
                i++;
                model.addRow(row);
                
            }
            db.disconect();
        } catch (Exception e) {
           e.printStackTrace();
        }
        
    }

    private void Search_textKeyReleased(java.awt.event.KeyEvent evt) {
        
        LocalDateTime myDateObj = LocalDateTime.now();  
        DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("yyyy-MM-dd");  
        String formattedDate = myDateObj.format(myFormatObj); 
        String query = "SELECT * FROM bills WHERE bill_date LIKE '%"+Search_text.getText()+"%'";
        System.out.println(query);
        DefaultTableModel model = (DefaultTableModel) Search_Table.getModel();
        model.setRowCount(0);
        try {
            Database db = new Database();
            db.getConnect();
            ResultSet rs = db.getStatement().executeQuery(query);
            int i = 1;
            while (rs.next()) {
                
                String bill_id = rs.getString("bill_id");
                String date = rs.getString("bill_date");
                String total_amount = rs.getString("total_amount");

                Object[] row = { i,bill_id,total_amount, date };
                i++;
                model.addRow(row);
                
            }
            db.disconect();
        } catch (Exception e) {
           e.printStackTrace();
        }
    }

    private void Delete_btnActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Delete History To day");
    
        DefaultTableModel model = (DefaultTableModel) Search_Table.getModel();
        String order_id = Search_Table.getValueAt(Search_Table.getSelectedRow(), 1).toString();
        String query = "DELETE FROM bill_items WHERE bill_id = "+order_id+"";
        int confirm = JOptionPane.showConfirmDialog(this, "คุณเเน่ใช่หรือไม่ว่าต้องการลบ รายการนี้ !", "Confirm Alert", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
           System.err.println(query);
            try {
                Database db = new Database();
                db.getConnect();
                db.getStatement().executeUpdate(query);
                db.disconect();
                model.removeRow(Search_Table.getSelectedRow());
            } catch (Exception e) {
                e.printStackTrace();
            }
            
            try {
                Database db = new Database();
                db.getConnect();
                db.getStatement().executeUpdate("DELETE FROM bills WHERE bill_id = "+order_id+"");

                db.disconect();
               
                
                db.disconect();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        
    }

    private void Search_TableMouseClicked(java.awt.event.MouseEvent evt) {
      

        String id = Search_Table.getValueAt(Search_Table.getSelectedRow(), 1).toString();
        String totalPrice = Search_Table.getValueAt(Search_Table.getSelectedRow(), 2).toString();
        String date = Search_Table.getValueAt(Search_Table.getSelectedRow(), 3).toString();
        
        String query = "SELECT * FROM bill_items WHERE bill_id = "+id+"";
        System.out.println(query);
        try {
            Database db = new Database();
            db.getConnect();
            ResultSet rs = db.getStatement().executeQuery(query);
            DefaultTableModel model = (DefaultTableModel) Table_Order.getModel();
            model.setRowCount(0);
            int i = 1;
            while (rs.next()) {
                String product_name = rs.getString("product_name");
                String price = rs.getString("price");
                String quantity = rs.getString("quantity");
                Object[] row = { product_name, price, quantity };
                i++;
                model.addRow(row);
            }
            
            db.disconect();
        } catch (Exception e) {
            e.printStackTrace();

        }

        upDatePrice();
        
    }

    public void addOrderToTable(String name, String price, int amount) {
        DefaultTableModel model = (DefaultTableModel) Table_Order.getModel();
        Object[] row = { name,price, amount };
        model.addRow(row);
        upDatePrice();
    }

    public void upDatePrice() {
        int discount = 0;
        int totalPrice = 0;
        int Price = 0;

        if (Table_Order.getRowCount() > 0) {
            
            
            for (int i = 0; i < Table_Order.getRowCount(); i++) {
                String price = (String) Table_Order.getValueAt(i, 1);
                int amount = Integer.parseInt(Table_Order.getValueAt(i, 2).toString());
                totalPrice += Integer.parseInt(price) * amount;
                Price += Integer.parseInt(price) * amount;
            }

            Price_textFeild.setText(String.valueOf(totalPrice));
            Discount_textFeild.setText("");

            if (totalPrice >= 100 && totalPrice < 200) {
                discount = 5;
                Discount_textFeild.setText("5");
            } else if (totalPrice >= 200 && totalPrice < 300) {
                discount = 10;
                Discount_textFeild.setText("10");
            } else if (totalPrice >= 300) {
                discount = 20;
                Discount_textFeild.setText("20");
            } else {
                discount = 0;
                if ( Table_Order.getRowCount() != 0 ) {
                
                }
            
            }

            if (discount > 0) {
                int total = totalPrice - discount;
                if (total > 0) {
                    totalPrice_textFeild.setText(String.valueOf(total));
                }
                
            } else {
            
                totalPrice_textFeild.setText(String.valueOf(Price));   
            } 

        } else {
            Price_textFeild.setText("");
            Discount_textFeild.setText("");
            totalPrice_textFeild.setText("");
        }

        

    }

    private int getOrderID() {
        int bill_id = 0;
      
        String query = "SELECT bill_id FROM bills";
        try {
            // Assuming you have a connection object named "connection"
            Database db = new Database();
            db.getConnect();
            ResultSet rs = db.getStatement().executeQuery(query);
            
            while (rs.next()) {
                bill_id = rs.getInt("bill_id");
            }
            
            rs.close();
            db.disconect();
            return bill_id;
        } catch (SQLException e) {
            e.printStackTrace();
        }

        System.out.println();
        
        return bill_id;
    }

    private int getLatestBillID() {
        int bill_id = 0;
      
        String query = "SELECT bill_id FROM bills ORDER BY bill_id DESC LIMIT 1";
        try {
            // Assuming you have a connection object named "connection"
            Database db = new Database();
            db.getConnect();
            ResultSet rs = db.getStatement().executeQuery(query);
            
            if (rs.next()) {
                bill_id = rs.getInt("bill_id");
            }
            
            rs.close();
            db.disconect();
            return bill_id;
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return bill_id;
    }
    


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(menuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(menuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(menuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(menuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
        
        try {
            
            UIManager.setLookAndFeel( new FlatLightLaf() );
        } catch( UnsupportedLookAndFeelException ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new menuPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bakery;
    private javax.swing.JPanel BakeryPanel;
    private javax.swing.JPanel Blueberry_Cake1;
    private javax.swing.JPanel Blueberry_Cake2;
    private javax.swing.JPanel Blueberry_Cake3;
    private javax.swing.JButton CakeSom_btn;
    private javax.swing.JSpinner CakeSom_count;
    private javax.swing.JButton Chatai_btn;
    private javax.swing.JSpinner Chatai_count;
    private javax.swing.JButton CheckOut_Btn;
    private javax.swing.JButton CheeseCake_btn;
    private javax.swing.JSpinner CheeseCake_count;
    private javax.swing.JButton Chocolate_btn;
    private javax.swing.JSpinner Chocolate_count;
    private javax.swing.JButton ClearOrder_Btn;
    private javax.swing.JButton Coco_btn;
    private javax.swing.JSpinner Coco_count;
    private javax.swing.JButton Delete_Order;
    private javax.swing.JButton Delete_btn;
    private javax.swing.JTextField Discount_textFeild;
    private javax.swing.JButton Drink;
    private javax.swing.JPanel DrinkPanel;
    private javax.swing.JButton Exit_Button;
    private javax.swing.JButton Food;
    private javax.swing.JPanel FoodPanel;
    private javax.swing.JButton KapaoKai_Btn;
    private javax.swing.JButton KapaoSea_Btn;
    private javax.swing.JButton KungWunSen_Btn;
    private javax.swing.JSpinner Kung_count;
    private javax.swing.JButton Makarone_btn;
    private javax.swing.JButton Pepsi_Btn;
    private javax.swing.JSpinner Pepsi_count;
    private javax.swing.JTextField Price_textFeild;
    private javax.swing.JButton RedCake_btn;
    private javax.swing.JSpinner RedCake_count;
    private javax.swing.JPanel Red_ake;
    private javax.swing.JPanel Red_ake1;
    private javax.swing.JPanel Red_ake2;
    private javax.swing.JPanel Red_ake3;
    private javax.swing.JPanel Red_ake4;
    private javax.swing.JPanel Red_ake5;
    private javax.swing.JPanel Report;
    private javax.swing.JButton Reported;
    private javax.swing.JTable Search_Table;
    private javax.swing.JButton Search_btn2;
    private javax.swing.JTextField Search_text;
    private javax.swing.JTable Table_Order;
    private javax.swing.JButton Water_Btn;
    private javax.swing.JSpinner Water_count;
    private javax.swing.JButton banoffee_btn;
    private javax.swing.JSpinner banoffee_count;
    private javax.swing.JButton capucuno_btn;
    private javax.swing.JSpinner capucuno_count;
    private javax.swing.JPanel chocolate_Cake;
    private javax.swing.JPanel chocolate_Cake1;
    private javax.swing.JPanel chocolate_Cake2;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton19;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner18;
    private javax.swing.JSpinner jSpinner20;
    private javax.swing.JSpinner kapaoKai_count;
    private javax.swing.JSpinner kapaosea_count;
    private javax.swing.JButton latae_btn;
    private javax.swing.JSpinner latae_count;
    private javax.swing.JPanel mainMenu;
    private javax.swing.JSpinner makarone_count;
    private javax.swing.JButton sapagetti_Btn;
    private javax.swing.JSpinner sapagetti_count;
    private javax.swing.JTextField totalPrice_textFeild;
    // End of variables declaration//GEN-END:variables

}